import { GoogleGenAI, Modality } from "@google/genai";

export const generateProfessionalHeadshot = async (
  base64ImageData: string,
  mimeType: string,
  prompt: string
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY as string });

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64ImageData,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        const generatedBase64 = part.inlineData.data;
        return `data:image/png;base64,${generatedBase64}`;
      }
    }

    throw new Error("No image was generated by the model. The response may have been blocked.");

  } catch (error) {
    console.error("Error generating image with Gemini:", error);
    if (error instanceof Error) {
        return Promise.reject(new Error(error.message));
    }
    return Promise.reject(new Error("An unknown error occurred while communicating with the Gemini API."));
  }
};